### ISSUE TITLE
Adding implementation for `Default`

### ISSUE THREAD

**Issue by mkeeter** [AdrienChampion/safe_index#1]
Quick question: are you interested in a PR which adds `impl Default for IndexType` to the index types, returning `IndexType::new(0)`?

(also, I'm excited to discover this library – it's something I've always wanted when wrangling flat buffers of data!)

**Comment by AdrienChampion** [comment]
I have no problem with an `impl Default` :)
I'm curious what your use-case is though, would you mind elaborating a bit?

(Thank you for your interest and excitement!)

**Comment by mkeeter** [comment]
I'm use the safe indexes to store handles in flat vectors (for computational geometry), so I'll have a

```
#[derive(Clone, Copy, Debug)]
struct Node {
    // edge counterclockwise from this node
    edge: EdgeIndex,

    // prev and next refer to traveling counterclockwise around the hull
    prev: PointIndex,
    next: PointIndex,
}
```

(where `edge` / `prev` / `next` point to typed vecs)

It's convenient to `#[derive(Default)]` for the whole data structure, so I can then use `Node::default()` when initializing `Node`'s with unknown values.

This also makes the index symmetric with `usize`, which implements `Default` returning 0.

PR open in #2 😃

**Comment by AdrienChampion** [comment]
Thank you for the explanation and the PR 😺 

Deriving `Default` goes against `safe_index`'s *original* philosophy: indices must be created by collections only, thus ensuring they are legal (at least for the collection that created a given index).

As you are probably aware, `safe_index` does not actually respect this philosophy because indices have a `new` constructor taking a `usize`, implement `From<usize>`, *etc.*

So, I am wondering whether it would be better to put `new` and the implementations for `Default`, `From<usize>`, ... behind a feature `from_int` or something. What do you think?

**Comment by mkeeter** [comment]
That's an interesting philosophical point!

One other example of using `Index::new(...)`: if I'm about to push three edges (pointing at each other) into a half-edge data structure, I'll create the indices beforehand, so I won't need to mutate them after pushing:

```rust
let i = self.edges.len();
let e_ab = EdgeIndex::new(i);
let e_bc = EdgeIndex::new(i + 1);
let e_ca = EdgeIndex::new(i + 2);
self.edges.push(Edge {
    src: a, dst: b,
    prev: e_ca, next: e_bc,
});
self.edges.push(Edge {
    src: b, dst: c,
    prev: e_ab, next: e_ca,
});
self.edges.push(Edge {
    src: c, dst: a,
    prev: e_bc, next: e_ab,
});
```

I'm not sure what other folks are doing with the library, but I'm fine with hiding the less-safe functions behind a `from_int` feature; I'll just immediately opt in 😃 .

(If you do this, you'd also probably want to gate `AddAssign` and `Add`, and note that it's still be possible to get an invalid index from a _different_ container of the same index type)

**Comment by AdrienChampion** [comment]
@mkeeter I think you would be better off using `<safe_index_map>.next_index()` instead of `<safe_index_map>.len()`, so that you don't ever manipulate `usize` values explicitly.

> (If you do this, you'd also probably want to gate `AddAssign` and `Add`, and note that it's still be possible to get an invalid index from a _different_ container of the same index type)

Well, you can get invalid indices with just one collection if you use `pop`, or even `next_index()`, since it gives you an illegal index.

The reason why I pointed out the (original) philosophy of the library is because I'm trying to assess whether it would be worth it to have the library actually guarantee that all indices are safe, always; with some clever type constraints to specialize indices on a particular map, and rework the API to remove all index *"constructors"* but `push`. Then have features to activate `pop`, `usize`  symmetry and such for those that want it.

If you have an opinion on this matter, I'd love to hear it :D
